# Generated by Django 4.2.23 on 2025-06-22 18:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("social", "0002_profile_profile_pic_recipe_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_recipes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
